name: Build ÖbEngine plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Compile ÖbEngine plugin
      uses: ObEngine/BuildPluginAction@v3
      with:
        obengineVersion: "v0.5"
        releaseAs: false

  build_macos:
    runs-on: macos-latest
    steps:
    - name: Compile ÖbEngine plugin
      uses: ObEngine/BuildPluginAction@v3
      with:
        obengineVersion: "v0.5"
        releaseAs: false

  build_windows:
    runs-on: windows-latest
    steps:
    - name: Compile ÖbEngine plugin
      uses: ObEngine/BuildPluginAction@v3
      with:
        obengineVersion: "v0.5"
        releaseAs: false